#controllers:
    #resource: ../src/Controller/
    #type: annotation

#kernel:
    #resource: ../src/Kernel.php
    #type: annotation
    #requirements:
        #_locale: en|fr
homepage:
  path: /{_locale}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  requirements:
    _locale: '%app.locales%'
  defaults:
    template: blog/homepage.html.twig
    _locale: '%locale%'
